import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import Navbar from "@/components/navbar";

const geistPoppins = Geist({
  variable: "--font-geist-poppins",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistPoppins.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <Navbar />
        {/* Main content */}
        <main className="max-w-[75rem] mx-auto">{children}</main>
      </body>
    </html>
  );
}
